### ISSUE TITLE
saveLevel error

### ISSUE THREAD

**Issue by XakepSDK** [Shevchik/AutoSaveWorld#11]
I'm using this version of asw:
AutoSaveWorld v4.14.1 
When i use save command, i get error:
asw save

[22:16:46 WARN]: [AutoSaveWorld] Could not dump RegionFileCache
[22:16:46 WARN]: java.lang.RuntimeException: Can't find method saveLevel with params length 0
[22:16:46 WARN]: at autosaveworld.utils.ReflectionUtils.getMethod(ReflectionUtils.java:49)
[22:16:46 WARN]: at autosaveworld.threads.save.AutoSaveThread.dumpRegionCache(AutoSaveThread.java:165)
[22:16:46 WARN]: at autosaveworld.threads.save.AutoSaveThread.performSave(AutoSaveThread.java:152)
[22:16:46 WARN]: at autosaveworld.threads.save.AutoSaveThread.run(AutoSaveThread.java:87)
Core:
kcauldron 1.7.10-1481.145

**Comment by Shevchik** [comment]
Use latest dev build

**Comment by XakepSDK** [comment]
Самому скомпилить или из jenkins взять?

**Comment by XakepSDK** [comment]
Работает, взял из jenkins. Спасибо.
