### ISSUE TITLE
Crash - java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by L4BORG** [Shevchik/AutoSaveWorld#17]
```
[16:38:34 ERROR]: Error occurred while disabling AutoSaveWorld v4.15.dev (Is it up to date?)
java.util.ConcurrentModificationException
        at org.bukkit.craftbukkit.v1_8_R3.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:297) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.saveChunks(ChunkProviderServer.java:332) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at net.minecraft.server.v1_8_R3.WorldServer.save(WorldServer.java:952) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:771) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.save(CraftWorld.java:762) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at autosaveworld.threads.save.AutoSaveThread.saveWorldNormal(AutoSaveThread.java:163) ~[?:?]
        at autosaveworld.threads.save.AutoSaveThread.saveWorld(AutoSaveThread.java:154) ~[?:?]
        at autosaveworld.threads.save.AutoSaveThread.performSaveNow(AutoSaveThread.java:84) ~[?:?]
        at autosaveworld.core.AutoSaveWorld.onDisable(AutoSaveWorld.java:126) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:454) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:81) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:85) [spigot-factions.jar:git-PaperSpigot-7aa4900-62a2169]
```

Any idea why I'm getting those over and over again... crashing my server each time? :(

**Comment by Shevchik** [comment]
This can't crash your server, because this occurs after plugin disable.
You may want to check your other plugins, maybe some of them does something with chunks async.

**Comment by L4BORG** [comment]
Yeah, I just found it misconfigured AAC caused that (looks like they've updated config format again). Sorry and thanks for explanation ;)
