### ISSUE TITLE
функция regioncashdump вываливает в консоль ошибки

### ISSUE THREAD

**Issue by Krysinski** [Shevchik/AutoSaveWorld#23]
вот такая ошибка:
[23:48:16 WARN]: [AutoSaveWorld] Could not dump RegionFileCache
[23:48:16 WARN]: java.lang.RuntimeException: Can't find method saveLevel with params length 0
[23:48:16 WARN]:        at autosaveworld.utils.ReflectionUtils.getMethod(ReflectionUtils.java:49)
[23:48:16 WARN]:        at autosaveworld.threads.save.AutoSaveThread.dumpRegionCache(AutoSaveThread.java:165)
[23:48:16 WARN]:        at autosaveworld.threads.save.AutoSaveThread.performSave(AutoSaveThread.java:152)
[23:48:16 WARN]:        at autosaveworld.threads.save.AutoSaveThread.run(AutoSaveThread.java:87)

Читал пост от 2014, где ты объяснял про важность этой функции для сохранения изменений в чанках. Скажи, сейчас это актуально еще для 1710 котла или термоса, т.е. без включения этой функции всё будет сохранятся?
Если тебе мой предыдущий вопрос о испорченных конфигах показался грубым, то извини.
Я не настолько тупой, правда. Без кавычек вполне работает с временем до 12:00, кавычки исчезают сами, но я перепроверю. На данный момент, оставшееся время прописал в командах.
EDIT:
проверил , кавычки с метки времени в разделе autorestart сами пропадают после перезагрузки сервера. Можешь открыть https://github.com/Shevchik/AutoSaveWorld/issues/22, я опишу всё там как здесь.

**Comment by Krysinski** [comment]
нашел похожее https://github.com/Shevchik/AutoSaveWorld/issues/11
У меня 882 билд, последний. До этого этой функцией не пользовался и были проблемы с сохранением мира. В данный момент работаю на Thermos 1.7.10-1614.46.

**Comment by Shevchik** [comment]
ХЗ, с котлом 100 лет не работал и скорее всего работать больше не буду.
И да, для котла должен искаться другой метод, если же кто-то опять переименовал имя сервера с cauldron на что-то другое, то это не моя проблема, разработчик такого ядра может идти нахер.
