### ISSUE TITLE
Периодическая ошибка в консоли (в логах)

### ISSUE THREAD

**Issue by Krysinski** [Shevchik/AutoSaveWorld#29]
`[15:28:41] [Server thread/WARN]: [AutoSaveWorld] Something attempted to access socket://185.5.248.216:7240 in main server thread, printing stack trace
[15:28:41] [Server thread/WARN]: java.lang.Exception: Stack trace
[15:28:41] [Server thread/WARN]:    at java.lang.Thread.dumpStack(Thread.java:1329)
[15:28:41] [Server thread/WARN]:    at autosaveworld.features.networkwatcher.NetworkWatcherProxySelector.select(NetworkWatcherProxySelector.java:61)
[15:28:41] [Server thread/WARN]:    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
[15:28:41] [Server thread/WARN]:    at java.net.Socket.connect(Socket.java:589)
[15:28:41] [Server thread/WARN]:    at java.net.Socket.connect(Socket.java:538)
[15:28:41] [Server thread/WARN]:    at launcher.request.Request.request(Request.java:41)
[15:28:41] [Server thread/WARN]:    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:42)
[15:28:41] [Server thread/WARN]:    at cyano.lootable.entities.EntityLootableBody.updatePlayerProfile(EntityLootableBody.java:152)
[15:28:41] [Server thread/WARN]:    at cyano.lootable.entities.EntityLootableBody.setOwner(EntityLootableBody.java:119)
[15:28:41] [Server thread/WARN]:    at cyano.lootable.entities.EntityLootableBody.func_70037_a(EntityLootableBody.java:305)
[15:28:41] [Server thread/WARN]:    at net.minecraft.entity.Entity.func_70020_e(Entity.java:1672)
[15:28:41] [Server thread/WARN]:    at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:173)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:487)
[15:28:41] [Server thread/WARN]:    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44)
[15:28:41] [Server thread/WARN]:    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
[15:28:41] [Server thread/WARN]:    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[15:28:41] [Server thread/WARN]:    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[15:28:41] [Server thread/WARN]:    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:212)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.World.func_72964_e(World.java:799)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.World.func_147439_a(World.java:702)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.World.func_147466_a(World.java:3317)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.SpawnerAnimals.func_77190_a(SpawnerAnimals.java:254)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:168)
[15:28:41] [Server thread/WARN]:    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:257)
[15:28:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
[15:28:41] [Server thread/WARN]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[15:28:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[15:28:41] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[15:28:41] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)`
Использую ASW исключительно для удаления неактивных игроков и их приватов. Логи заполняются этой ошибкой.

**Comment by Shevchik** [comment]
Not an asw error. Something attempted to access network in main thread which i bad.

**Comment by Krysinski** [comment]
Это понятно и так. Я бы желал чтобы ASW не портил логи мне и всё. Ставлю - в логах эта фигня вылазит, убираю ASW - логи чистые. Опцию может в конфигах добавишь?
Прошу открыть вопрос.

**Comment by Krysinski** [comment]
вот схожая проблема https://dev.bukkit.org/bukkit-plugins/autosaveworld/tickets/50-error-something-attempted-to-access-socket-api-mojang/

**Comment by Krysinski** [comment]
Есть решение: вырубить эту фигню в конфиге ASW (в самом низу конфига  warn: false):
`networkwatcher:
  mainthreadnetaccess:
    warn: false
    interrupt: false`
***взято отсюда http://rubukkit.org/threads/voprosy-po-oshibkam-v-konsoli.56041/page-95
