### ISSUE TITLE
Working build for 1.4.7 (FTB Ultimate)?

### ISSUE THREAD

**Issue by Zyles** [Shevchik/AutoSaveWorld#3]
Is there a working version for Feed the Beast Ultimate which runs MC 1.4.7. And I run MCPC+ legacy on the server.

I install the jar and console says:

> asw
> 00:23:23 [INFO] Unknown command. Type "help" for help.

**Comment by Shevchik** [comment]
It should, check the startup log, maybe there is something wrong here.

**Comment by Zyles** [comment]
I can't even find a message in the startup or shutdown about anything AutoSaveWorld related.

I dropped the jar into plugins directory. Anything else?

**Comment by Shevchik** [comment]
Dropping jar to plugins directory should be enough.
Check /plugin list after loading, if AutoSaveWorld isn't here that server doesn't even try to load plugin.

**Comment by Zyles** [comment]
No it's not there. All other plugins I have are loaded fine.

Running this:
https://bitbucket.org/OniBait/mcpc-plus

**Comment by Shevchik** [comment]
Post startup log somewhere maybe i can see what's wrong.

**Comment by Zyles** [comment]
Found this:

2014-01-23 00:17:05 [SEVERE] Could not load 'plugins/AutoSaveWorld.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassNotFoundException: Failed to remap class autosaveworld.core.AutoSaveWorld
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:176)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugins(CraftServer.java:263)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.<init>(CraftServer.java:241)
    at gm.<init>(ServerConfigurationManager.java:122)
    at hn.<init>(DedicatedPlayerList.java:19)
    at ho.c(DedicatedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613)
    at fy.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: Failed to remap class autosaveworld.core.AutoSaveWorld
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:357)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:271)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:247)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:165)
    ... 9 more
Caused by: java.lang.UnsupportedClassVersionError: autosaveworld/core/AutoSaveWorld : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:345)
    ... 16 more

**Comment by Shevchik** [comment]
Update your java to java7.

**Comment by Zyles** [comment]
Thanks, looks like Ubuntu runs an older version. Works now.
