### ISSUE TITLE
Only backup when players online

### ISSUE THREAD

**Issue by Zyles** [Shevchik/AutoSaveWorld#4]
I think you really need to add this option. Or it will just create duplicate backups. And A LOT of them.

**Comment by Zyles** [comment]
My small world is up to 5 GB in storage now because of the redundant backups on empty server.

**Comment by Shevchik** [comment]
I'm working in system that will skip backup if there wasn't any players online from last backup

**Comment by iampyrex** [comment]
Is this what causes:

[AutoSaveWorld] Could not dump RegionFileCache
[04:59:47] [AutoSaveWorld AutoSaveThread/WARN]: java.lang.RuntimeException: Can't find method saveLevel with params length 0
[04:59:47] [AutoSaveWorld AutoSaveThread/WARN]:         at autosaveworld.utils.ReflectionUtils.getMethod(ReflectionUtils.java:49)
[04:59:47] [AutoSaveWorld AutoSaveThread/WARN]:         at autosaveworld.threads.save.AutoSaveThread.dumpRegionCache(AutoSaveThread.java:165)
[04:59:47] [AutoSaveWorld AutoSaveThread/WARN]:         at autosaveworld.threads.save.AutoSaveThread.performSave(AutoSaveThread.java:152)
[04:59:47] [AutoSaveWorld AutoSaveThread/WARN]:         at autosaveworld.threads.save.AutoSaveThread.run(AutoSaveThread.java:87)

**Comment by Shevchik** [comment]
No

**Comment by SavageCore** [comment]
Any updates to this?

**Comment by Shevchik** [comment]
No, because there can be activity when there are 0 players online, so that feature is in a low priority list.
