### ISSUE TITLE
Issue with ftp backup

### ISSUE THREAD

**Issue by darkarrow** [Shevchik/AutoSaveWorld#43]
When ever I try to backup to an FTP server I get this error:
> [04:02:02 ERROR]: [AutoSaveWorld] Failed FTP backup
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_151]
at java.util.Arrays$ArrayList.<init>(Arrays.java:3813) ~[?:1.8.0_151]
at java.util.Arrays.asList(Arrays.java:3800) ~[?:1.8.0_151]
at autosaveworld.features.backup.ftp.FTPVirtualFileSystem.getEntries(FTPVirtualFileSystem.java:96) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.ftp.FTPVirtualFileSystem.exists(FTPVirtualFileSystem.java:64) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.utils.virtualfilesystem.VirtualFileSystem.createDirectory(VirtualFileSystem.java:44) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.utils.virtualfilesystem.VirtualFileSystem.createAndEnterDirectory(VirtualFileSystem.java:29) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.utils.virtualfilesystem.VirtualBackupManager.backup(VirtualBackupManager.java:69) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.ftp.FTPBackup.performBackup(FTPBackup.java:69) ~[AutoSaveWorld.jar:?]
at autosaveworld.features.backup.AutoBackupThread.performBackup(AutoBackupThread.java:103) [AutoSaveWorld.jar:?]
at autosaveworld.features.backup.AutoBackupThread.doTask(AutoBackupThread.java:60) [AutoSaveWorld.jar:?]
at autosaveworld.utils.Threads$IntervalTaskThread.run(Threads.java:103) [AutoSaveWorld.jar:?]

I also tried updating to the latest on the jenkins server and it's still the same error

**Comment by darkarrow** [comment]
I changed passive to true and it seems to be working now
