### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vlader97** [Shevchik/AutoSaveWorld#48]
Spigot 1.12.2
Autosaveworld v4.15

Plugin often generate this error:
```
[13:42:25] [Server thread/WARN]: [AutoSaveWorld] Something attempted to access socket://api.mojang.com:443 in main server thread, printing stack trace
[13:42:25] [Server thread/WARN]: java.lang.Exception: Stack trace
[13:42:25] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[13:42:25] [Server thread/WARN]: 	at autosaveworld.features.networkwatcher.NetworkWatcherProxySelector.select(NetworkWatcherProxySelector.java:61)
[13:42:25] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
[13:42:25] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[13:42:25] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[13:42:25] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
[13:42:25] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
[13:42:25] [Server thread/WARN]: 	at com.mojang.authlib.HttpAuthenticationService.performPostRequest(HttpAuthenticationService.java:77)
[13:42:25] [Server thread/WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66)
[13:42:25] [Server thread/WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:54)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:64)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:1)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[13:42:25] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:1)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull.b(TileEntitySkull.java:222)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:81)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:431)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:45)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:293)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:334)
[13:42:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:428)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:42:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:42:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:42:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:42:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:42:26] [Server thread/WARN]: [AutoSaveWorld] Something attempted to access socket://sessionserver.mojang.com:443 in main server thread, printing stack trace
[13:42:26] [Server thread/WARN]: java.lang.Exception: Stack trace
[13:42:26] [Server thread/WARN]: 	at java.lang.Thread.dumpStack(Thread.java:1336)
[13:42:26] [Server thread/WARN]: 	at autosaveworld.features.networkwatcher.NetworkWatcherProxySelector.select(NetworkWatcherProxySelector.java:61)
[13:42:26] [Server thread/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
[13:42:26] [Server thread/WARN]: 	at java.net.Socket.connect(Socket.java:589)
[13:42:26] [Server thread/WARN]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
[13:42:26] [Server thread/WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[13:42:26] [Server thread/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[13:42:26] [Server thread/WARN]: 	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:130)
[13:42:26] [Server thread/WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:66)
[13:42:26] [Server thread/WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180)
[13:42:26] [Server thread/WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:79)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:1)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
[13:42:26] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:1)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.TileEntitySkull.b(TileEntitySkull.java:222)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:81)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:431)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:45)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItem(CraftWorld.java:293)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.dropItemNaturally(CraftWorld.java:334)
[13:42:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:428)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1005)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1311)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1621)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:42:26] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:42:26] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:42:26] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:42:26] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Shevchik** [comment]
Not an asw error.

**Comment by Vlader97** [comment]
ok if not asw error why is shows ?
How I remove him?

**Comment by Shevchik** [comment]
[AutoSaveWorld] Something attempted to access socket://api.mojang.com:443 in main server thread, printing stack trace
It literally tells you why it shows. If you don't know why it is bad - go learn how minecraft server works.
So you either fix that in the server, or disable network watcher in autosaveworld config.
