### ISSUE TITLE
Error on saving map

### ISSUE THREAD

**Issue by Elikill58** [Shevchik/AutoSaveWorld#72]
Hello,

I have install your plugin, and i just see that it create some error:
` [AutoSaveWorld] Could not dump RegionFileCache
java.lang.RuntimeException: Can't find method saveLevel with params length 0
        at autosaveworld.utils.ReflectionUtils.getMethod(ReflectionUtils.java:49) ~[AutoSaveWorld.jar:?]
        at autosaveworld.features.save.AutoSaveThread.dumpRegionCache(AutoSaveThread.java:135) [AutoSaveWorld.jar:?]
        at autosaveworld.features.save.AutoSaveThread.performSave(AutoSaveThread.java:122) [AutoSaveWorld.jar:?]
        at autosaveworld.features.save.AutoSaveThread.doTask(AutoSaveThread.java:70) [AutoSaveWorld.jar:?]
        at autosaveworld.utils.Threads$IntervalTaskThread.run(Threads.java:103) [AutoSaveWorld.jar:?]`

(Latest version)

**Comment by Elikill58** [comment]
Fixed in #64 (waiting merge)
