### ISSUE TITLE
Not starting up on KCauldron - java.lang.NoClassDefFoundError: autosaveworld/threads/worldregen/WorldRegenPasteThread

### ISSUE THREAD

**Issue by Katelyn-SN** [Shevchik/AutoSaveWorld#9]
```
[21:30:52 ERROR]: Error occurred while enabling AutoSaveWorld v4.15.dev (Is it up to date?)
java.lang.NoClassDefFoundError: autosaveworld/threads/worldregen/WorldRegenPasteThread
        at autosaveworld.core.AutoSaveWorld.onEnable(AutoSaveWorld.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1420.104]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1420.104]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1420.104]
        at me.jmgr2007.Reloader.Utils.load(Utils.java:154) [Reloader.jar:?]
        at me.jmgr2007.Reloader.ReloaderListener.onCommand(ReloaderListener.java:96) [Reloader.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1420.104]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1420.104]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-1420.104]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:1.7.10-1420.104]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
```

**Comment by Shevchik** [comment]
Do not relace jars at runtime. Use update folder if you want to reload plugin.
